
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060102
// Mon May 04 11:30:16 CEST 2009
//----------------------------------------------------

package g;

/** CUP generated interface containing symbol constants. */
public interface SokoParserSym {
  /* terminals */
  public static final int INCR = 17;
  public static final int MOB = 10;
  public static final int UGUALE = 14;
  public static final int INT = 22;
  public static final int TC = 21;
  public static final int WIDTH = 4;
  public static final int END = 7;
  public static final int DECR = 18;
  public static final int IF = 6;
  public static final int PV = 25;
  public static final int ID = 23;
  public static final int EOF = 0;
  public static final int HEIGHT = 3;
  public static final int DIVERSO = 19;
  public static final int VIR = 24;
  public static final int FISSI = 11;
  public static final int NMOB = 9;
  public static final int error = 1;
  public static final int GOAL = 12;
  public static final int DIM = 8;
  public static final int FOR = 5;
  public static final int MAGUG = 16;
  public static final int TO = 20;
  public static final int SOKO = 13;
  public static final int MINUG = 15;
  public static final int VAR = 2;
}

